id: IBB5B5A8D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:44:49+00:00'
last_modified: '2022-06-08T06:28:39.060681+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3916
  title: གསུང་འབུམ། པདྨ་རྣམ་རྒྱལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C398:
      image_group_id: I2871
      title: ''
      total_pages: 766
      order: 1
      base_file: C398.txt
    EF09:
      image_group_id: I2872
      title: ''
      total_pages: 614
      order: 2
      base_file: EF09.txt
    '2613':
      image_group_id: I2873
      title: ''
      total_pages: 606
      order: 3
      base_file: 2613.txt
    D036:
      image_group_id: I2874
      title: ''
      total_pages: 518
      order: 4
      base_file: D036.txt
    A8F8:
      image_group_id: I2875
      title: ''
      total_pages: 506
      order: 5
      base_file: A8F8.txt
    '6445':
      image_group_id: I2876
      title: ''
      total_pages: 472
      order: 6
      base_file: 6445.txt
    '3323':
      image_group_id: I2877
      title: ''
      total_pages: 734
      order: 7
      base_file: 3323.txt
    '4902':
      image_group_id: I2878
      title: ''
      total_pages: 616
      order: 8
      base_file: 4902.txt
    '9725':
      image_group_id: I2879
      title: ''
      total_pages: 683
      order: 9
      base_file: 9725.txt
    5E06:
      image_group_id: I2880
      title: ''
      total_pages: 1049
      order: 10
      base_file: 5E06.txt
    DE2E:
      image_group_id: I2881
      title: ''
      total_pages: 724
      order: 11
      base_file: DE2E.txt
    42E6:
      image_group_id: I2882
      title: ''
      total_pages: 830
      order: 12
      base_file: 42E6.txt
    A277:
      image_group_id: I2883
      title: ''
      total_pages: 556
      order: 13
      base_file: A277.txt
    5FAE:
      image_group_id: I2884
      title: ''
      total_pages: 600
      order: 14
      base_file: 5FAE.txt
    AA75:
      image_group_id: I2885
      title: ''
      total_pages: 638
      order: 15
      base_file: AA75.txt
    0B0C:
      image_group_id: I2886
      title: ''
      total_pages: 740
      order: 16
      base_file: 0B0C.txt
    2F8E:
      image_group_id: I2887
      title: ''
      total_pages: 533
      order: 17
      base_file: 2F8E.txt
    EE99:
      image_group_id: I2888
      title: ''
      total_pages: 712
      order: 18
      base_file: EE99.txt
    6FFB:
      image_group_id: I2889
      title: ''
      total_pages: 549
      order: 19
      base_file: 6FFB.txt
    E789:
      image_group_id: I2890
      title: ''
      total_pages: 2
      order: 20
      base_file: E789.txt
    B63C:
      image_group_id: I2891
      title: ''
      total_pages: 2
      order: 21
      base_file: B63C.txt
    '2888':
      image_group_id: I2892
      title: ''
      total_pages: 2
      order: 22
      base_file: 2888.txt
    911A:
      image_group_id: I2893
      title: ''
      total_pages: 2
      order: 23
      base_file: 911A.txt
    AE43:
      image_group_id: I2894
      title: ''
      total_pages: 2
      order: 24
      base_file: AE43.txt
    4ED0:
      image_group_id: I2895
      title: ''
      total_pages: 710
      order: 25
      base_file: 4ED0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
